---
title: "240302 Aerobic recapitualtion of SIgA-driven stationary cell death of TT8"
author: "Morgan"
date: "`r format(Sys.time(), '%a, %b %d, %Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

# Setup

## Libraries

```{r}
library(dplyr)
library(ggplot2)
library(magrittr)
library(readr)
library(tidyr)
library(readxl)
library(ggthemes)
library(RColorBrewer)
```

## Parameters

```{r}
# Source locations
src_dir <- paste0("~/Documents/Stanford/Huang_lab_rotation/SIgA_cell_physiology/",
                  "240302_aerobic_TT8_SIgA_recapitulate/")

raw_file <- "240228_TT8_SIgA_aerobic_recapitulation_raw.xlsx"

# Destination locations
dst_dir <- "~/Documents/repositories/BIOS216_final_project/outputs/"
```

------------------------------------------------------------------------

# Computation

## File transformation

```{r}
# Read all csv files
gc_ <- read_excel(file.path(src_dir, raw_file))

# Convert all numerical values to doubles and save as a copy of the raw import
gc <- gc_ %>%
  as.data.frame(lapply(gc_, as.double))

# Preview tibble
head(gc)
```

------------------------------------------------------------------------

## Raw data manipulation

```{r}
# Generate table of relevant values only
relevant_gc <- gc %>%
  select(Time, D2:D11, E4:E9) %>%
  mutate("0ugmL_SIgA" = rowMeans(select(., D3:D6)),
         "30ugmL_SIgA" = rowMeans(select(., D7:D10)),
         "300ugmL_SIgA" = rowMeans(select(., E5:E8)),
         blank = rowMeans(select(., D2, D11, E4, E9)))

# Blank all values
for (col_name in names(relevant_gc)) {
  relevant_gc[[col_name]] <- relevant_gc[[col_name]] - relevant_gc$blank
}

# Calculate SD values for each class and add them as columns
zero_ugmL_SD <- apply(gc[, c("D3", "D4", "D5", "D6")], 1, sd)
thrty_ugmL_SD <- apply(gc[, c("D7", "D8", "D9", "D10")], 1, sd)
thrhnd_ugmL_SD <- apply(gc[, c("D3", "D4", "D5", "D6")], 1, sd)
relevant_gc_SD <- relevant_gc %>%
  cbind(., "0ugmL_SD" = zero_ugmL_SD) %>%
  cbind(., "30ugmL_SD" = thrty_ugmL_SD) %>%
  cbind(., "300ugmL_SD" = thrhnd_ugmL_SD)

# Add upper and lower bounds
relevant_gc_SD <- relevant_gc_SD %>%
  mutate("0_lower" = .data$'0ugmL_SIgA' - .data$'0ugmL_SD',
         "0_upper" = .data$'0ugmL_SIgA' + .data$'0ugmL_SD',
         "30_lower" = .data$'30ugmL_SIgA' - .data$'30ugmL_SD',
         "30_upper" = .data$'30ugmL_SIgA' + .data$'30ugmL_SD',
         "300_lower" = .data$'300ugmL_SIgA' - .data$'300ugmL_SD',
         "300_upper" = .data$'300ugmL_SIgA' + .data$'300ugmL_SD')

# Clean up final tibble and export to .csv object
final_gc <- relevant_gc_SD %>%
  select(., -c(D2:E9, blank))

write.csv(final_gc, paste0(dst_dir, "final_gc.csv"))

# Preview tibble
head(final_gc)
```

------------------------------------------------------------------------

## Combined growth curves

```{r}
# Generate growth curves of all conditions
gc_combined_plot <- ggplot(final_gc, aes(x = Time)) + 
  geom_line(aes(y = .data$'0ugmL_SIgA', col = "0ugmL_SIgA")) + 
  geom_line(aes(y = .data$'30ugmL_SIgA', col = "30ugmL_SIgA")) + 
  geom_line(aes(y = .data$'300ugmL_SIgA', col = "300ugmL_SIgA")) + 
  labs(x = "Time (min)", y = "OD", col = NULL, 
       title = "Aerobic growth of TT8 +/- SIgA") + 
  scale_color_brewer(palette = "Set1") + 
  theme_classic() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "bottom")

gc_combined_plot
```

## Singular growth curves with error envelopes

```{r}
# Generate separate envelope curves for each condition
gc_0ugmL <- ggplot(final_gc, aes(x = Time)) + 
  geom_line(aes(y = .data$'0ugmL_SIgA'), col = "darkred") + 
  geom_ribbon(aes(ymin = .data$'0_lower', ymax = .data$'0_upper'), 
              fill = "darkred", alpha = 0.2) +
  coord_cartesian(ylim = c(0, 1.3)) + 
  labs(x = "Time (min)", y = "OD", 
       title = "Aerobic growth of TT8") + 
  theme_classic() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "bottom")

gc_30ugmL <- ggplot(final_gc, aes(x = Time)) +
  geom_line(aes(y = .data$'30ugmL_SIgA'), col = "darkgreen") + 
  geom_ribbon(aes(ymin = .data$'30_lower', ymax = .data$'30_upper'), 
              fill = "darkgreen", alpha = 0.2) +
  coord_cartesian(ylim = c(0, 1.3)) +
  labs(x = "Time (min)", y = "OD", 
       title = "Aerobic growth of TT8 + 30 ug/mL SIgA") + 
  scale_color_brewer(palette = "Set1") + 
  theme_classic() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "bottom")

gc_300ugmL <- ggplot(final_gc, aes(x = Time)) +
  geom_line(aes(y = .data$'300ugmL_SIgA'), col = "darkblue") + 
  geom_ribbon(aes(ymin = .data$'300_lower', ymax = .data$'300_upper'), 
              fill = "darkblue", alpha = 0.2) + 
  coord_cartesian(ylim = c(0, 1.3)) + 
  labs(x = "Time (min)", y = "OD",
       title = "Aerobic growth of TT8 + 300 ug/mL SIgA") + 
  scale_color_brewer(palette = "Set1") + 
  theme_classic() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "bottom")

gc_0ugmL
gc_30ugmL
gc_300ugmL

```

## Outputs

```{r}
ggsave("transformed_growth_curve_data.png", final_gc_table, path = dst_dir, device = "png")

```

------------------------------------------------------------------------

# Dependencies

```{r}
# Clean up project of libraries not in use
renv::clean()

# Update lock file with new packages
renv::snapshot()
```

------------------------------------------------------------------------

# Documentation

## Session info

```{r}
print(sessionInfo(), locale = FALSE)
```

## References

```{r}
(.packages()) %>%
  sort() %>%
  lapply(citation) %>%
  lapply(c) %>%
  unique()
```
